version: 2.1

commands:
  prepare:
    steps:
      - show_node_version
      - show_yarn_cache_location
  restore_yarn_cache:
    steps:
      - run: node -v > .node_version
      - restore_cache:
          keys:
            - yarn-packages-{{ arch }}-{{ checksum ".node_version" }}-{{ checksum "yarn.lock" }}
            - yarn-packages-{{ arch }}-{{ checksum ".node_version" }}-
  save_yarn_cache:
    steps:
      - run: node -v > .node_version
      - save_cache:
          key: yarn-packages-{{ arch }}-{{ checksum ".node_version" }}-{{ checksum "yarn.lock" }}
          paths:
            - /home/circleci/.cache/yarn
  show_node_version:
    steps:
      - run:
          name: show node version
          command: |
            echo "node version: $(node -v)"
            echo "npm version: $(npm -v)"
            echo "yarn version: $(yarn -v)"
  show_yarn_cache_location:
    steps:
      - run: yarn cache dir

jobs:
  test:
    docker:
      - image: circleci/node:14
    steps:
      - prepare
      - checkout
      - restore_yarn_cache
      - run: yarn install
      - save_yarn_cache
      - run: yarn jest
  release:
    docker:
      - image: circleci/node:14
    steps:
      - prepare
      - checkout
      - restore_yarn_cache
      - run: yarn install
      - save_yarn_cache
      - add_ssh_keys:
          fingerprints:
            - '62:80:8b:e4:f0:e2:7b:9b:6e:ae:c3:3c:97:eb:74:c2'
      - run:
          name: Login npm
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
            npm whoami
      - run: yarn lerna version --yes --conventional-commits --create-release github
workflows:
  version: 2
  test-and-release:
    jobs:
      - test
      - release:
          requires:
            - test
          filters:
            branches:
              only:
                - master
